#!/bin/bash

if [[ -z "$HOSTNAME" ]]; then
    HOSTNAME=$(hostname -s)-$RANDOM
fi

if [[ -z "$WEBMUX_HOST" ]]; then
    WEBMUX_HOST="webmux.e.ip.saba.us"
fi
if [[ -z "$WEBMUX_SSH_KEY_FILE" ]]; then
    WEBMUX_SSH_KEY_FILE="~/etc/secure/ssh/external/webmux_rsa"
fi

KEYSCAN="|1|5MOtL8p91Mye7t1QHVqWGy3vh4A=|t2HEPsfvD2Qhg2se60DK8HOnGc0= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDUeo1sjImOIuV3O88JjW1H+H7QXxF1Otkw5eTHPbopjMvof1SykFOuEhIW7csxJN9vS+2Vly3mvHljTIcJcRlQ="
if [[ -z $(grep "$KEYSCAN" ~/.ssh/known_hosts) ]]; then
    echo "$KEYSCAN" >> ~/.ssh/known_hosts
fi

if [[ -z "$(which timeout)" ]] && [[ -z "$(which gtimeout)" ]]; then
    if [[ "$PLATFORM" == "Darwin" ]]; then
        brew install coreutils
    elif [[ -n "$(which apt-get)" ]]; then
        sudo apt-get install coreutils
    elif [[ -n "$(which yum)" ]]; then
        sudo yum install coreutils
    else
        echo "ERROR: timeout not found, and I don't know how to install it!"
    fi
fi

function get_port_mapping()
{
    curl -f -L "https://$WEBMUX_HOST/register/$HOSTNAME/$USER" 2>/dev/null
}

function webmux_reverse_tunnel()
{
    if [[ -n "$(which gtimeout)" ]]; then
        gtimeout 1h $(which ssh) -i "$(echo $WEBMUX_SSH_KEY_FILE)" -N -R $1:localhost:22 "webmux@$WEBMUX_HOST"
    else
        timeout 1h $(which ssh) -i "$(echo $WEBMUX_SSH_KEY_FILE)" -N -R $1:localhost:22 "webmux@$WEBMUX_HOST"
    fi
}

while [ true ]; do
    PORT_NUMBER=$(get_port_mapping)
    if [[ -z "$PORT_NUMBER" ]]; then
        if (( "$PORT_MAP_FAILURES" < 10 )); then
            echo "ERROR: Could not get port mapping; Sleeping for $((PORT_MAP_FAILURES*10)), then trying again (try $PORT_MAP_FAILURES)"
            sleep $((PORT_MAP_FAILURES*10))
            continue
        fi
        echo "ERROR: Could not get port mapping; bailing after $PORT_MAP_FAILURES tries!"
        exit 1
    fi
    echo "Connecting on port $PORT_NUMBER..."
    webmux_reverse_tunnel $PORT_NUMBER
    sleep 1
done
