#!/bin/bash

if [[ -z "$HOSTNAME" ]]; then
    HOSTNAME=$(hostname -s)-$RANDOM
fi

function get_port_mapping()
{
    curl -f -L "https://webmux.e.ip.saba.us/register/$HOSTNAME" 2>/dev/null
}

function webmux_reverse_tunnel()
{
    $(which ssh) -N -R $1:localhost:22 webmux@saba.us
}

while [ true ]; do
    PORT_NUMBER=$(get_port_mapping)
    if [[ -z "$PORT_NUMBER" ]]; then
        echo "ERROR: Could not get port mapping; bailing..."
        exit 1
    fi
    echo "Connecting on port $PORT_NUMBER..."
    webmux_reverse_tunnel $PORT_NUMBER
    sleep 1
done
